logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

server:
  port: 8080

shareit-server:
  url: http://localhost:9090/

hikari:
  connection-timeout: 60000
  validation-timeout: 5000
